channels:
  - bioconda
  - conda-forge
dependencies:
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - libcxx=9.0.1=1
  - libffi=3.2.1=1
  - ncurses=6.1=h0a44026_1002
  - openssl=1.1.1d=h0b31af3_0
  - pip=20.0.2=py_2
  - python=3.7.6=hfa4aa89_3_cpython
  - readline=8.0=hcfe32e1_0
  - setuptools=45.2.0=py37_0
  - sqlite=3.30.1=h93121df_0
  - tk=8.6.10=hbbe82c9_0
  - wheel=0.34.2=py_1
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h0b31af3_1006
  - pip:
    - biopython==1.76
    - cycler==0.10.0
    - dna-features-viewer==3.0.1
    - soothsayer-utils==2020.3.27
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - numpy==1.18.1
    - pandas==1.0.1
    - pathlib2==2.3.5
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - scandir==1.10.0
    - six==1.14.0
    - tqdm==4.43.0
    - tzlocal==2.0.0
